typography_spectrum: 0.7200790918432176
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.012976785190403461
  lightness: 0.20105286710895598
  saturation: 0.7867109344806522
  rhythmicContrast: 0.37741500744596124
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.13110942533239722
analytics:
  google: null
  facebook: null
  twitter: null
name: Andrew Scudder
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: asdasda
purpose: []
